name: wejoeco
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  dio_cache_interceptor: ^3.5.1
  shared_preferences: ^2.5.2
  path_provider: ^2.1.5
  dio_cache_interceptor_hive_store: ^4.0.0
  get_it: ^8.0.3
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  permission_handler: ^11.4.0
  image_picker: ^1.1.2
  shimmer: ^3.0.0
  pie_chart: ^5.0.0
  intl: ^0.20.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  #assets:
    #- assets/Images/
